### יצירת תגובה חדשה
POST http://localhost:3000/comment
Content-Type: application/json

{
  "post": "63af44b0c9d1a45fdb741e2d",
  "content": "This is a great comment!",
  "sender": "12345"
}

POST http://localhost:3000/comments/create
Content-Type: application/json

{
  "post": "63af44b0c9d1a45fdb741e2d",
  "content": "This is a comment!",
  "sender": "12345"
}


### שליפת כל התגובות
GET http://localhost:3000/comments

### שליפת תגובות לפי פוסט
GET http://localhost:3000/comment?post=63af44b0c9d1a45fdb741e2d

### עדכון תגובה
PUT http://localhost:3000/comment/63af44b0c9d1a45fdb741e2d
Content-Type: application/json

{
  "content": "Updated comment text!"
}

### מחיקת תגובה
DELETE http://localhost:3000/comment/63af44b0c9d1a45fdb741e2d
