@postId = 677985c87ec88218105db60e
@commentId = 677985d57ec88218105db612
@baseUrl = http://localhost:3000


############ POSTS Requests: ############

### Add a New Post:
POST {{@baseUrl}}/posts
Content-Type: application/json

{
    "title": "Bad Romance",
    "owner": "LadyGaga",
    "content": "Caught in a bad romance"
}

### Get All Posts (All posts):
GET {{@baseUrl}}/posts

### Get All Posts (Filtered by Owner):
GET {{@baseUrl}}/posts?owner=LadyGaga

### Get a Post by ID:
GET {{@baseUrl}}/posts/{{@postId}}

### Update a Post:
PUT {{@baseUrl}}/posts/{{@postId}}
Content-Type: application/json

{
    "title": "Diamonds",
    "owner": "Rihanna",
    "content": "Shine bright like a diamond"
}


