@baseUrl = http://localhost:3000
@postId = 6790f406c80f3fed27504c7a
@commentId = 6790f445c80f3fed27504c82

############ COMMENTS Requests: ############

### Add a new comment
POST {{baseUrl}}/comments/comment
Content-Type: application/json

{
  "post": "{{postId}}",
  "content": "This is a comment",
  "sender": "beyonce"
}

### Get comments by post ID
GET {{baseUrl}}/comments?post={{postId}}

### Get all comments
GET {{baseUrl}}/comments/all

### Update a comment
PUT {{baseUrl}}/comments/comment/{{commentId}}
Content-Type: application/json

{
  "content": "Updated comment content"
}

### Delete a comment
DELETE {{baseUrl}}/comments/comment/{{commentId}}

############ POSTS Requests: ############

### Add a New Post
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "title": "Bad Romance",
  "owner": "LadyGaga",
  "content": "Caught in a bad romance"
}


### Get All Posts (All posts)
GET {{baseUrl}}/posts

### Get All Posts (Filtered by Owner)
GET {{baseUrl}}/posts?owner=LadyGaga

### Get a Post by ID
GET {{baseUrl}}/posts/{{postId}}

### Update a Post
PUT {{baseUrl}}/posts/{{postId}}
Content-Type: application/json

{
  "title": "Diamonds",
  "owner": "Rihanna",
  "content": "Shine bright like a diamond"
}

### Delete a Post
DELETE {{baseUrl}}/posts/{{postId}}